import React, { useState, useEffect } from 'react';

const ESTADO_COLORS = {
  activa:     'badge-calificado',
  pausada:    'badge-contactado',
  finalizada: 'badge-perdida',
  planificada:'badge-oportunidad',
};

function estadoBadge(estado) {
  if (!estado) return <span className="badge badge-nuevo">—</span>;
  const cls = ESTADO_COLORS[estado.toLowerCase()] || 'badge-nuevo';
  return <span className={`badge ${cls}`}>{estado.charAt(0).toUpperCase() + estado.slice(1)}</span>;
}

export default function CampaniaDetail({ campania, leads = [], onBackClick, baseApiUrl }) {
  const [beneficios, setBeneficios] = useState(null);
  const [cargandoBeneficios, setCargandoBeneficios] = useState(false);

  useEffect(() => {
    const fetchBeneficios = async () => {
      setCargandoBeneficios(true);
      try {
        const res = await fetch(`${baseApiUrl}/campanias/${campania.id}/beneficios`);
        if (res.ok) {
          const data = await res.json(); // { sumaContratos: BigDecimal }
          setBeneficios(data.sumaContratos);
        }
      } catch (e) {
        console.error('Error fetching beneficios de campaña:', e);
      } finally {
        setCargandoBeneficios(false);
      }
    };
    if (campania?.id) {
      fetchBeneficios();
    }
  }, [campania, baseApiUrl]);

  // Filter leads generated by this campaign
  // The backend JPA entity Lead still links to Campania, so we can filter here
  const campaniaLeads = leads.filter(l => l.campania?.id === campania.id);

  const fmtDate = (iso) => {
    if (!iso) return '—';
    return new Date(iso).toLocaleDateString('es-AR', { day: '2-digit', month: '2-digit', year: 'numeric' });
  };

  const fmtMoney = (v) =>
    v != null ? `$${Number(v).toLocaleString('es-AR')}` : '—';

  // Calculate ROI: costo / beneficios (sumaContratos)
  // ROI in the project is calculated as: costo de campaña / suma de contratos obtenidos.
  // Lower ROI is better since it means less cost per dollar earned.
  const roi = beneficios > 0 && campania.costo != null
    ? (Number(campania.costo) / Number(beneficios)).toFixed(4)
    : null;

  return (
    <>
      <div className="page-header">
        <div className="page-header-left">
          <button 
            className="btn btn-secondary btn-sm" 
            style={{ marginBottom: '12px', display: 'inline-flex', alignItems: 'center', gap: '6px' }}
            onClick={onBackClick}
          >
            ← Volver al listado
          </button>
          <h2>Detalle de Campaña</h2>
          <p>Información estratégica, rendimiento y leads generados</p>
        </div>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '24px', alignItems: 'start' }}>
        
        {/* Ficha de datos */}
        <div className="card" style={{ padding: '24px' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '20px', borderBottom: '1px solid var(--border)', paddingBottom: '16px' }}>
            <div>
              <span style={{ fontSize: '12px', color: 'var(--gray-400)', fontFamily: 'monospace' }}>
                CAMPAÑA #{campania.id}
              </span>
              <h3 style={{ margin: '4px 0 0 0', fontSize: '20px', fontWeight: 700, color: 'var(--gray-900)' }}>
                {campania.nombre}
              </h3>
            </div>
            {estadoBadge(campania.estado)}
          </div>

          <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px' }}>
              <div>
                <label style={{ display: 'block', fontSize: '12px', color: 'var(--gray-400)', fontWeight: 500, textTransform: 'uppercase', marginBottom: '4px' }}>
                  Tipo de Campaña
                </label>
                <div style={{ fontSize: '14.5px', color: 'var(--gray-800)', fontWeight: 600 }}>
                  {campania.tipo || '—'}
                </div>
              </div>

              <div>
                <label style={{ display: 'block', fontSize: '12px', color: 'var(--gray-400)', fontWeight: 500, textTransform: 'uppercase', marginBottom: '4px' }}>
                  Costo Asignado
                </label>
                <div style={{ fontSize: '14.5px', color: 'var(--gray-800)', fontWeight: 600, fontFamily: 'monospace' }}>
                  {fmtMoney(campania.costo)}
                </div>
              </div>
            </div>

            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px' }}>
              <div>
                <label style={{ display: 'block', fontSize: '12px', color: 'var(--gray-400)', fontWeight: 500, textTransform: 'uppercase', marginBottom: '4px' }}>
                  Fecha de Inicio
                </label>
                <div style={{ fontSize: '14.5px', color: 'var(--gray-800)' }}>
                  {fmtDate(campania.fechaInicio)}
                </div>
              </div>

              <div>
                <label style={{ display: 'block', fontSize: '12px', color: 'var(--gray-400)', fontWeight: 500, textTransform: 'uppercase', marginBottom: '4px' }}>
                  Fecha de Fin
                </label>
                <div style={{ fontSize: '14.5px', color: 'var(--gray-800)' }}>
                  {fmtDate(campania.fechaFin)}
                </div>
              </div>
            </div>

            <div>
              <label style={{ display: 'block', fontSize: '12px', color: 'var(--gray-400)', fontWeight: 500, textTransform: 'uppercase', marginBottom: '4px' }}>
                Descripción de la Campaña
              </label>
              <div style={{ fontSize: '14.5px', color: 'var(--gray-700)', lineHeight: '1.5', background: 'var(--gray-50)', padding: '10px 12px', borderRadius: 'var(--radius)', border: '1px solid var(--border)' }}>
                {campania.descripcion || 'Sin descripción registrada.'}
              </div>
            </div>
          </div>
        </div>

        {/* Ficha de Rendimiento & Leads */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: '24px' }}>
          
          {/* Rendimiento Financiero ROI */}
          <div className="card" style={{ padding: '24px' }}>
            <h3 style={{ margin: '0 0 16px 0', fontSize: '16px', fontWeight: 600, color: 'var(--gray-800)', display: 'flex', alignItems: 'center', gap: '8px' }}>
              <span>📊</span> Rendimiento y ROI Comercial
            </h3>

            {cargandoBeneficios ? (
              <div style={{ fontSize: '14px', color: 'var(--gray-400)' }}>Calculando beneficios...</div>
            ) : (
              <div style={{ display: 'flex', flexDirection: 'column', gap: '14px' }}>
                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px' }}>
                  <div style={{ background: 'var(--gray-50)', padding: '12px', borderRadius: 'var(--radius)', border: '1px solid var(--border)' }}>
                    <span style={{ fontSize: '11px', color: 'var(--gray-400)', textTransform: 'uppercase', fontWeight: 600 }}>Contratos Obtenidos</span>
                    <div style={{ fontSize: '18px', fontWeight: 700, color: 'var(--gray-900)', fontFamily: 'monospace', marginTop: 4 }}>
                      {fmtMoney(beneficios)}
                    </div>
                  </div>

                  <div style={{ 
                    background: roi !== null ? 'var(--primary-light)' : 'var(--gray-50)', 
                    padding: '12px', 
                    borderRadius: 'var(--radius)', 
                    border: roi !== null ? '1px solid #dbeafe' : '1px solid var(--border)'
                  }}>
                    <span style={{ fontSize: '11px', color: roi !== null ? 'var(--primary)' : 'var(--gray-400)', textTransform: 'uppercase', fontWeight: 600 }}>ROI (Costo/Contrato)</span>
                    <div style={{ 
                      fontSize: '18px', 
                      fontWeight: 700, 
                      color: roi !== null ? 'var(--primary)' : 'var(--gray-900)', 
                      fontFamily: 'monospace', 
                      marginTop: 4 
                    }}>
                      {roi !== null ? roi : '—'}
                    </div>
                  </div>
                </div>
                {roi !== null && (
                  <span style={{ fontSize: '12px', color: 'var(--gray-400)', fontStyle: 'italic' }}>
                    * Un ROI menor indica una mayor eficiencia de la inversión (menor costo por dólar contratado).
                  </span>
                )}
              </div>
            )}
          </div>

          {/* Leads Generados */}
          <div className="card" style={{ padding: '24px' }}>
            <h3 style={{ margin: '0 0 16px 0', fontSize: '16px', fontWeight: 600, color: 'var(--gray-800)', display: 'flex', alignItems: 'center', gap: '8px' }}>
              <span>👥</span> Leads Generados por esta Campaña
            </h3>

            {campaniaLeads.length === 0 ? (
              <div style={{ padding: '16px', textAlign: 'center', color: 'var(--gray-400)', fontSize: '13.5px', background: 'var(--gray-50)', borderRadius: 'var(--radius)' }}>
                No hay leads generados por esta campaña en este momento.
              </div>
            ) : (
              <div style={{ maxHeight: '200px', overflowY: 'auto', display: 'flex', flexDirection: 'column', gap: '8px', paddingRight: '4px' }}>
                {campaniaLeads.map(l => (
                  <div 
                    key={l.id} 
                    style={{ 
                      padding: '10px 14px', 
                      background: 'var(--gray-50)', 
                      borderRadius: 'var(--radius)', 
                      border: '1px solid var(--border)',
                      display: 'flex',
                      justifyContent: 'space-between',
                      alignItems: 'center'
                    }}
                  >
                    <div>
                      <span style={{ fontSize: '13px', fontWeight: 600, color: 'var(--gray-800)' }}>{l.nombre}</span>
                      <span style={{ fontSize: '11px', color: 'var(--gray-400)', marginLeft: '8px', fontFamily: 'monospace' }}>#{l.id}</span>
                    </div>
                    <span className="badge badge-nuevo" style={{ fontSize: '11px', padding: '2px 6px' }}>{l.estado}</span>
                  </div>
                ))}
              </div>
            )}
          </div>

        </div>

      </div>
    </>
  );
}
